# Google App Engine configuration
runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_VERSION: "v1"

# MongoDB URI should be set via Google Secret Manager or in the GCP Console
# env_variables:
#   MONGODB_URI: "your-mongodb-connection-string"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
